kevinaangstadt/CS340-S23-Notes

Day9_File_Counts.md

Hi Kevin, this is a pull request to change the Day9 branch by updating linuxlab28.

Day9 Table Update

---

Day9_File_Counts.md

Updated the number of files for cslinuxlab-24

Added File Counts to Day9_File_Counts markdown file

---

Day9_File_Counts.md

Added a count of files in cslinuxlab-20.

Update Day9_File_Counts for cslinuxlab-20

---

Day9_File_Counts.md

Added Number of files associated to my home directory on CSLinuxlab-09

---

Day9_File_Counts.md

Updated the number of files for cslinuxlab-16 to contain the
correct number of files within the home directory.

Updated the number of files for cslinuxlab-16

---

Day9_File_Counts.md

Updated file value for linuxlab-06

---

Day9_File_Counts.md

Added the number of files from linux lab 19

Linuxlab-19 # of files in 100

---

Day9_File_Counts.md

Please pull from my repository, I added the number of files in my home directory to the Day_9 file .

Updated Day_9 file

---

lecture10.md

Add lecture 10 notes outline to class notes repository to meet project 2 checkpoint requirement.
Future work of inserting actual notes content from lecture 10.

Add lecture 10 notes outline

---

Lecture17.md

Small file to indicate that progress is being made on lecture 17, and to complete instructor checkpoint. Content will be based on topics covered in the 3/15/2023 software engineering lecture.

Add lecture 17 outline

---

lecture9.md

This md file contains an outline for lecture
nine's, left blank in order for notes to be
filled out at a later time.

Lecture Nine Notes Outline

---

Lecture11.md

Add a file outlining the lesson and discussion in Lecture 11 to complete the instructor checkpoint. Content will be based on topics covered in 2/22/2023.

Add Outline for Lecture 11. 

---

lecture4.md

Created day 4 branch for lecture 4 notes.
Updated formatting for lecture 4 outline.

Add day 4 branch for lecture 4 notes

---

lecture_16.md

Added  Lecture 16 outline for 3/13 class

Lecture 16 outline

---

lecture12.md

Created a lecture12.md file for that day's notes.
Committed to satisfy checkpoint 1 requirements.

Add lecture 12 file outline

---

LectureNotes/Lecture26_4-24.md

Currently the file is empty since we havent had this class yet

Add lecture notes for day 26, 4-24

---

Lecture14_3-6.md

The file will later be filled with the notes for lecture 14.

Add outline of notes for lecture 14 (03/06/23) for project 2 checkpoint.

---

Lecture_Notes_3_29_23.md

Created the lecture notes for 3/29/23 to be filled in for a later date.

Lecture Notes outline added for 3/29/23

---

2_13_23_day8_outline.md

There was no outline for lecture 8. In this pull request is an outline for lecture 8 on Feb. 13, 2023. This day discusses fetching, rebasing, and merging. This outline is to meet project 2 checkpoint.

Day 8 outline

---

Day9_File_Counts.md

-Accept pull request for updated file count of Day9

- Update file count to 9519

---

StyleGuideOutline.md

Add outline of style guide to class notes repo for project 2 checkpoint requirements. Next need to create style guide based on outline.

Add style guide outline

---

Lecture-3

This patch is meant to update the Lecture 3 Branch and provide an outline for the lecture notes to be recorded at a future date.

Creating Lecture 3 Outline

---

Exam1StudyGuide.md

Add outline of study guide for Exam 1 (occuring on 01/03/2023) in order to submit pull requst for p2 checkpoint.

Add outline of Exam 1 Study Guide

---

Lecture21.md

Lecture note outline for Day 21 containing lecture contents for that day.

Lecture 21

---

3_27_23Notes.md
Day9_File_Counts.md

Adding Machines 21 number of files for day 9

Day 9 File Count

---

Lecture21.md

Reverts kevinaangstadt/CS340-S23-Notes#90

Revert "Lecture 21"

---

5-1-23-Class-Notes.md
OUTLINE.md
README.md

This commit is a branch off of the main workflow and will change the CS340 notes. Although this commit will only add text to the CS340 notes page that was provided. Because this is a checkpoint this is just simply a commit to show we are able to properly branch from main and make our own workflow.

Add to checkpoint1 project2

---

lecture12.md
lecture12_2-27.md

This pull request completes notes for lecture 12 which was about measuring quality of software testing.
This class covered measuring quality of testing, test suite quality metrics, and issues that can go wrong with testing. This class also gave us an outline on what would be on Exam 1.

Update and rename lecture12.md to lecture12_2-27.md

---

Day17Notes.md
Lecture17.md

This pull request contains two commits.
Commit one focuses on the topics covered in lecture 17, such as making software work with partially implemented features, control flow graphs, and automated test generation.
Commit two focuses on the in-class fuzz testing python script.

Completion of Lecture17

---

Day9Notes.md

This commit updates the lecture 12 notes document. The first change that was made to this document is changing the name of the file to align with the style guide. The second change to this file is the addition of an overview section at the begining of the document. The remaining changes were making minor formating changes to better align with the style guide.

Edits the Lecture 12 Notes

---

Exam1StudyGuide.md

This file did not have an overview as specified by the Style guide and has now been added to match.

Addition of an Overview Section to Exam1StudyGuide.md

---

Day9_File_Counts.md

As a task for Day 9 of CS-340 Sp 2023, students will practice checking out a repository and submitting changes with a pull request.  This file gives students a place to submit a modification to a file.  On each linuxlab machine, students will count the number of files in their home directory and update the table accordingly.

Add File Counts markdown file

---

Day12Notes.md

- Add a something fun section to Day12Notes.md
- The section should now include an embedded link with a gif
- The something fun section is not necessary but encouraged
- Add a something fun section to adhere to the encouraged specifications in the style guide

Update Day12Notes.md Something Fun Section

---

Exam1StudyGuide.md

Based on style guidelines (#116 ) , added in a "funny meme" and re-formatted any in line definitions to match the style guide.
Old definition Style
>### Word
> the definition
Proper definition style
>### Definition
> Word - the definition

Fix Errors for - Exam1StudyGuide.md

---

Day11Notes.md

This pull request is for changes made to Day11Notes. I changed minor grammatical errors by changing lowercase letters to upper case letters to enhance the quality of the notes.

Fixed minor grammatical errors for Day 11

---

Day3Notes.md

This commit updates some content of the notes to match formatting per the style guide.  This commit also adds an overview of the lecture to the file. Lastly, this commit updates the name of the file to match the style guide requirements.

Update and rename Lecture-3 to Day3Notes.md

---

Day27Notes.md
lecture-27.md

This commit also changes the title of the markdown file to be consistent with classmates..

Add content to lecture 27, 5/1/23

---

lecture23.md

This is a final version of my Lecture 23 summary. I added the sudo code for delta debugging and erased "lecture 23 outline"

Final lecture23.md

---

Day22Notes.md

This adds an overview section at the top of the page just to summarize the day notes.

Add overview section to Day22Notes.md
